### ISSUE TITLE
Apostrophe exits with error when apostrophe-browserify is installed and configured

### ISSUE THREAD

**Issue by madarche** [punkave/apostrophe-browserify#6]
When `apostrophe-browserify` is installed and configured, Apostrophe exits with the following error:

```shell
/tmp/test-project$ node app.js
/tmp/test-project/node_modules/moog/index.js:317
          if (key.substr(0, 2) === '__') {
                  ^

TypeError: key.substr is not a function
    at /tmp/test-project/node_modules/moog/index.js:317:19
    at Function.forEach (/tmp/test-project/node_modules/moog/node_modules/lodash/dist/lodash.js:3298:15)
    at applyOptions (/tmp/test-project/node_modules/moog/index.js:313:11)
    at /tmp/test-project/node_modules/moog/index.js:230:15
    at iterate (/tmp/test-project/node_modules/moog/node_modules/async/lib/async.js:146:13)
    at Immediate.<anonymous> (/tmp/test-project/node_modules/moog/node_modules/async/lib/async.js:157:25)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

To reproduce:

* Follow the exact steps described in the section "Generating a test project" of http://apostrophecms.org/docs/tutorials/getting-started/creating-your-first-project.html
* Then, as described in https://github.com/punkave/apostrophe-browserify, add the following module configuration:
    ```javascript
    'apostrophe-browserify': {
    // files are specified relative to the project directory (app.js)
    files: [ './public/js/modules/_site.js' ]
  }
    ```
* Create a `./public/js/modules/_site.js` file (for example with `alert('Hello world')` in it)
* Start Apostrophe

The fact that the `_site.js` file exists or not doesn't change anything. I have also tried to put different options in the `apostrophe-browserify` module configuration to no avail.

What I'm very surprised of, is that it is the `moog` package that crashes and not `apostrophe-browserify`: I don't understand what moog has to do with browserification. Is there a regression in some Apostrophe packages, or is there something missing in the apostrophe-browserify doc?

**Comment by boutell** [comment]
This module is for 0.5. we will deprecate it properly.

As the docs say, you don't need an Apostrophe module to do things at
project level with browserify. Just set up your own gulp workflow, where
the output file is an asset pushed to Apostrophe in the usual way.

**Comment by madarche** [comment]
@boutell thanks for your (always) fast answers! We were just wondering if and why `apostrophe-browserify` was a recommendation.
